server:
  port: 8018
  servlet:
    context-path: /admin

# admin
# client配置：spring.boot.admin.url=http://localhost:8018
spring:
  application:
    name: admin
  boot:
    admin:
      context-path: /sba
      client:
        prefer-ip: true

